name: Release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_BUILDKIT: 0
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      -
        name: Build and push Postgres Importer 16
        id: docker_build_16
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PG_VERSION=16.3
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            flyio/postgres-importer:16
            flyio/postgres-importer:16.3
      -
        name: Postgres Importer 16 Image digest
        run: echo ${{ steps.docker_build_16.outputs.digest }}
